In [6]:
# ------ Task 1 ------
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def process_arrays():
    global arr_1d, arr_2d
    print("1D array:", arr_1d)
    print("2D array:\n", arr_2d)
    print("Sum of 1D array:", np.sum(arr_1d))
    print("Mean of 2D array:", np.mean(arr_2d))
    print("Transpose of 2D array:\n", np.transpose(arr_2d))
process_arrays()

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of 1D array: 15
Mean of 2D array: 5.0
Transpose of 2D array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
# ------ Task 2 ------
import numpy as np
def process_image():
    image = np.random.randint(0, 256, (5, 5), dtype=np.uint8)
    print("Original Image:\n", image)
    cropped = image[1:4, 1:4]
    print("Cropped Section:\n", cropped)
    inverted_image = 255 - image
    print("Inverted Image:\n", inverted_image)
process_image()

Original Image:
 [[116  35 203 129  62]
 [ 29 207 125  85 230]
 [158 217 252 119 155]
 [141 228 165  80  95]
 [117  77 213 218 168]]
Cropped Section:
 [[207 125  85]
 [217 252 119]
 [228 165  80]]
Inverted Image:
 [[139 220  52 126 193]
 [226  48 130 170  25]
 [ 97  38   3 136 100]
 [114  27  90 175 160]
 [138 178  42  37  87]]
